version: "3.3"

services:
  redis:
    container_name: "uyir_redis"
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - db:/data # Corrected Redis data path
    logging:
      driver: "none"

volumes:
  db:
